name: Run pytest

on:
  - pull_request
  - push

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Show Python
        run: |
          python -V
          python -c "import sys,platform;print('executable=',sys.executable);print('platform=',platform.platform())"

      - name: Install dependencies
        run: pip install '.[dev]'

      - name: Run pytest
        run: pytest --cov=grassmann_tensor --cov-branch --cov-report=xml

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: os-${{ matrix.os }}, python-${{ matrix.python-version }}
